# Generated by Django 5.0.1 on 2025-05-04 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_userrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_collaborative',
            field=models.BooleanField(default=False, help_text='Playlist có thể được chỉnh sửa bởi nhiều người cộng tác'),
        ),
        migrations.CreateModel(
            name='CollaboratorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EDITOR', 'Người chỉnh sửa'), ('VIEWER', 'Người xem')], default='VIEWER', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_collaborators', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='music.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlist_collaborator_roles',
                'unique_together': {('user', 'playlist')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborative_playlists', through='music.CollaboratorRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlaylistEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE_INFO', 'Cập nhật thông tin'), ('ADD_SONG', 'Thêm bài hát'), ('REMOVE_SONG', 'Xóa bài hát'), ('ADD_COLLABORATOR', 'Thêm cộng tác viên'), ('REMOVE_COLLABORATOR', 'Xóa cộng tác viên'), ('CHANGE_ROLE', 'Thay đổi vai trò'), ('RESTORE', 'Khôi phục')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text='Chi tiết về hành động chỉnh sửa')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='music.playlist')),
                ('related_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_history', to='music.song')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_history_mentions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlist_edit_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
