# Generated by Django 5.0.1 on 2025-05-04 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_is_collaborative_collaboratorrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ tải xuống'), ('DOWNLOADING', 'Đang tải xuống'), ('COMPLETED', 'Đã tải xuống hoàn tất'), ('FAILED', 'Tải xuống thất bại'), ('EXPIRED', 'Đã hết hạn')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_downloads', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offline_downloads',
                'ordering': ['-download_time'],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
