# Generated by Django 5.0.1 on 2025-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_offlinedownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Đánh dấu bài hát đã được phê duyệt'),
        ),
    ]
