# Generated by Django 5.0 on 2025-04-02 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('SONG', 'Song Share'), ('PLAYLIST', 'Playlist Share'), ('IMAGE', 'Image Message'), ('VOICE', 'Voice Message'), ('FILE', 'File Attachment')], default='TEXT', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/%Y/%m/%d/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/%Y/%m/%d/')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_messages', to=settings.AUTH_USER_MODEL)),
                ('shared_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='music.playlist')),
                ('shared_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='music.song')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
