# Generated by Django 5.0.1 on 2025-05-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_status',
            field=models.CharField(choices=[('NORMAL', 'Normal Content'), ('FLAGGED', 'Flagged by System'), ('REPORTED', 'Reported by User'), ('REVIEWED', 'Reviewed by Admin'), ('HIDDEN', 'Hidden by Admin')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='review_note',
            field=models.TextField(blank=True, help_text='Ghi chú của admin khi kiểm duyệt'),
        ),
        migrations.AddField(
            model_name='message',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('TEMPORARY', 'Hạn chế tạm thời'), ('PERMANENT', 'Hạn chế vĩnh viễn'), ('WARNING', 'Cảnh báo')], max_length=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_restrictions',
            },
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'Nội dung không phù hợp'), ('SPAM', 'Tin nhắn spam'), ('HARASSMENT', 'Quấy rối'), ('HATE_SPEECH', 'Phát ngôn thù ghét'), ('OTHER', 'Lý do khác')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('REVIEWED', 'Đã xem xét'), ('RESOLVED', 'Đã giải quyết'), ('DISMISSED', 'Bác bỏ')], default='PENDING', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, help_text='Hành động đã thực hiện đối với báo cáo này')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_reports',
            },
        ),
    ]
