# Generated by Django 5.0.1 on 2025-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_user_updated_at_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_content',
            field=models.BooleanField(default=False, verbose_name='Có thể quản lý nội dung'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_playlists',
            field=models.BooleanField(default=False, verbose_name='Có thể quản lý playlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Có thể quản lý người dùng'),
        ),
    ]
