# Generated by Django 5.0.1 on 2025-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_manage_content_user_can_manage_playlists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_manage_content',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_playlists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_users',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'Regular User')], default='user', max_length=10),
        ),
    ]
