# Generated by Django 5.0.1 on 2025-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='attempted_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
